---
title: Git to the Rescue
author: Martin Gleason, MS
date: '2018-05-10'
categories:
  - git
  - version control
tags:
  - git
  - GitHub
slug: git
---

What I love about `blogdown` is the way it almost everything I am learing in this project: R, documentation, version control, data as storytelling. My only issue with it is when something bad happens. This is more a question of familiarity than one of difficulty. For instance, if something broke on one of my old wordpress sites, if I couldn't diagnose and fix the issue quickly, I have friends and, in some cases, a dedicated tech support team to help me fix it. If I break something in `blogdown`, then I am the one who has to fix it. Fortunately, the R community (and especially Yiu Hie's leadership on the package), git tutorials, and Google lead to some quick fixes. The fixes would have been much faster if I wasn't in a panic and sick as a dog.

# What I did
I updated this project with a post on some early text mining/word cloud experiment. I took that bit from a much longer post on some survey data I collected for my podcast, [All Comics Considered](https://allcomicsconsidered.com). What I did not do with that longer post was mark it as a draft in the `yaml` header. I published it too soon. The first thing I did to remedy the situation was edit the date on unfinished post so it would appear a week later. Fix the issue by instituting a deadline. Between posting the [wordcloud](2018/05/word-cloud/) post and the date change fix, I managed to delete every other post I had made to this blog. 

(images/rocket_face_palm.gif)

I panicked. 

I knew `git` could recover deleted files. I initialy tried to pull from my github repo. When that didn't work, I started googling a better solution. I eventually found the `checkout` [command.](https://git-scm.com/docs/git-checkout). Since I was in already my blog's working directory (computer_name:adventures-in-data-science/), I pulled the log file and got a summary of all the files I deleted: `git log --diff-filter=D --summary .`  I tested the solution with the following: `git checkout [sha name]~1 00644 content/post/name_of_blog_post.rmd`. Like magic, that file reappeared. I loaded two other files by hand, before trying to recover the entire folder. As it happens, by deleteing the name of the blog post in the command, and just leaving `content/post` I was able to restore everytyhing I had deleted.

There was one other issue I needed to fix. While the live preview of `blogdown` worked, it was not updating on the website. After a few frustating minutes of thinking it was `git` I went to [netlify](https://netlify.com) and read the logs about why the build failed. As it turns out, when I recovered the deleted files, I also recovered a series of tags I deleted.[^1] Those tags, I remember, caused errors in hugo. I found the offending rmd file and removed it from the commit. After I pushed the commit to [github](https://github.com/martin-gleason), I manually redeployed the build by netlify, and restored everything I lost.[^2] Now the only thing left to fix is [Disquss.](https://disquss.com)

While I would have preferred to learn these `git` lessons when I was feeling better and less panicked, I did learn them. I hope that by posting this, I can save someone some time and anxiety if the run into a similar issue. I'm also sure there's an easier way to recover lost files via git-- So if you found this useful, or youknow a better way of doing recovering files, let me know in the Disquss comments!


[^1:] As it happen, I probably should have escaped the # in #Rstats, but I just deleted it.
[^2:] At that point, after being sick all night long, I went back to bed and didn't wake up until the dogs needed to go out.